import { Inter } from "next/font/google";
import "./globals.css";
import { AOSInit } from '@/app/lib/aos'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AOSInit />
      <body>
        {children}
      </body>
    </html>
  );
}
